DROP TYPE IF EXISTS shopping_category;
CREATE TYPE shopping_category AS ENUM (
   'Main',
   'Snack',
   'Lunch',
   'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT FALSE NOT NULL,
    category shopping_category NOT NULL
);

